### ISSUE TITLE
No notifications on iOS8 (only badge?!)

### ISSUE THREAD

**Issue by AndreasWidmer** [z-push-ox/z-push-ox#19] opened 2015-01-31 15:27 UTC
Hi,

thanks for your z-push backend!

I set everything up and tested with multiple z-push versions. The problem is, that I will not get any notifications if an email arrives. The count badge only counts after some time up. If I open the mail app (without having any notification or update on the badge) the email is fetched, but marked as read! After some time / refreshing, the mail gets marked as unread (and I think at this time the badge will count +1). Of course i have checked the notifications settings in iOS - and tried on 2 other iOS devices (iPhone 5 / 6 / iPad).

If I visit the https://xxx/Microsoft-Server-ActiveSync I can sign in with my credentials and everything seems fine. I have just set up the complete environment a second time to see if I made any mistakes :-/

My setup looks something like this:

Debian 7
POSTFIX / dovecot with virtual domains / users
Open-Xchange (latest version) with SSL in virtualhost (works everthing like a charm)
At the moment: Z-push 2.2 RC Beta (tried dpush as well - same behavior) with the additional packages (HTTP_Request2 Net_URL2) and the latest z-push-ox, git cloned into the backend folder.

In the z-push config added the Backend:
    define('BACKEND_PROVIDER', "BackendOX");
    define('OX_SERVER', 'http://127.0.0.1');

I hope someone can help me with this problem. It would be really awesome to have push on my mobile devices!

Thanks a lot.
Greetings

**Comment by andrzejwp** [comment] 2015-02-03 18:16
Hi, I can confirm This exact behavior.
Tested on iPhone 5s running iOS 8.1.2, 8.1.3, iPhone 4s with iOS 8.1.2
Z-push versions 2.1.0 And 2.1.3.
BackendOX HEAD.

In my case it seems that the Messages are first downloaded as READ and then after a couple of minutes or a manual fetch they regain their proper UNREAD status. At the same time Other clients properly display the message as unread...
I suppose that the ios mail app doesn't show or sound notifications because the email originally arrives as READ.

I'll be debugging This alter This evening, in case you need any particular logs - I'll probably have them.

Thanks for your input.

**Comment by AndreasWidmer** [comment] 2015-02-03 19:10
Hi,

glad to hear that it's not an configuration issue ;)
Yes, it is the same exact behavior as you describe.

I'm really not into the z-push system, so im afraid I can't help fixing this issue.

Thanks for your help.

**Comment by andrzejwp** [comment] 2015-02-03 20:20
Please confirm if my fork makes it work in your case (it does in mine)
https://github.com/cdwv/z-push-ox

**Comment by andrzejwp** [comment] 2015-02-03 20:25
I think there still is a major problem with the backend as it seems it only supports polling (no sink mechanism) and so it will probably quickly drain our batteries...

**Comment by AndreasWidmer** [comment] 2015-02-03 20:35
Thanks for your quick fix!
It looks like it works. New mails are shown as unread and there is an notification (in my case about 30 seconds after sending the message).

Unfortunately the problem with massive battery draining would be unhandy in an productive environment. :-/

**Comment by andrzejwp** [comment] 2015-02-03 20:46
Yeah, tell me about it. The 30 second lag is correct - it's the default   specified in

  define('PING_INTERVAL', 30);

 Please let me know if you observe excessive battery use. I'll look into this tomorrow, unless the backend's author helps us out.

**Comment by AndreasWidmer** [comment] 2015-02-03 20:48
I will report asap! Thank you for your help, Sir!

**Comment by liob** [comment] 2015-02-03 21:15
Hi,

thank you andrzejwp for taking a look at the issue. I am looking forward to your solution and would like to incorporate it in the repo.

Regarding the proposed polling problem:
Yes, zpush polls the emails from openxchange. However, if the client supports push, push will be used in the communication between client and zpush. This means, that the emails will have a slight delay of PING_INTERVAL in the worst case when being delivered to the client. Nonetheless, the battery should not be drained.

**Comment by andrzejwp** [comment] 2015-02-03 21:27
Hi, thanks for your quick response. I'll open a PR in a moment.
I'm not sure about the zpush part, according to z-push-top my iPhone seems to be in "polling" state no matter what. I take it from "Polling 33/900s on Email" in the Additional Information column. But maybe that's just my problem. AndreasWidmer - can you confirm? How does it look on your side?

**Comment by AndreasWidmer** [comment] 2015-02-03 21:47
Polling 120/1038s on policies and counting ...
But unfortunately no more pushes at the moment :-/

**Comment by liob** [comment] 2015-02-03 21:54
ok, so push is not working, however, the "read state" of the emails is correct?

**Comment by AndreasWidmer** [comment] 2015-02-03 21:56
Yes, looks like no push :-/ The first mail was pushed without any problems.

Does it still work for you after the first one? @andrzejwp

**Comment by liob** [comment] 2015-02-03 21:59
I do not think that the push issue is an issue of the backend (z-push-ox). Therefore I am closing this issue and merge pr #20

**Closed by liob** 2015-02-03 21:59 UTC

**Comment by andrzejwp** [comment] 2015-02-03 22:02
Neither do I. Thanks for merging.
Can we now both Check if push works with an imap backend?

**Comment by andrzejwp** [comment] 2015-02-03 22:07
There's something in z-push-top I dont understand - my connection is counted as Push yet the additional info says polling.
My xonnections seem to die and respawn frequently. There are periods when my phone is not reported in z-push-top And periods when it's only polling for contacts / calendar (?).
I'll have More info tomorrow during the day - I dont get a lot of emails at This hour so it's hard to check.

Andreas can you try connecting zpush directly to your imap server And check if it changes the behavior at all?=

**Comment by AndreasWidmer** [comment] 2015-02-04 21:05
Unfortunately it seems that I can't establish connection directly via IMAP :-/
After settings the imap server / port z-push can't auth with, in my case, dovecot (with virtual domains / users).
